#!/usr/bin/env bash
set -e

# ==============================================================================
# Interactive Manager & Installer for Google Drive Rclone Mount
# ==============================================================================

MOUNT_DIR="${HOME}/mnt/google_drive"
REMOTE_NAME="gdrive"
SERVICE_NAME="rclone-gdrive"
SYSTEMD_USER_DIR="${HOME}/.config/systemd/user"
CACHE_DIR="${HOME}/.cache/rclone"
RCLONE_CONF_DIR="${HOME}/.config/rclone"
RCLONE_CONF="${RCLONE_CONF_DIR}/rclone.conf"
READ_ONLY=false
FORCE_CLEAR=false
RUNNER_SCRIPT="${HOME}/.local/bin/rclone-gdrive-mount"
PIDFILE="${HOME}/.cache/rclone/rclone-gdrive.pid"

# True only when systemd is actually usable for --user units. Containers and
# WSL1 typically have no systemd as PID 1, so `systemctl --user` fails with
# "System has not been booted with systemd" / "Failed to connect to bus".
have_systemd() {
    [ -d /run/systemd/system ] || return 1
    command -v systemctl &>/dev/null || return 1
    systemctl --user show-environment &>/dev/null || return 1
    return 0
}

# --- VFS cache tuning (override via environment before running the script) ---
# VFS_CACHE_MAX_SIZE      Hard-ish cap on cached file data (soft: see README).
# VFS_CACHE_MAX_AGE       Evict cached files untouched for this long.
# VFS_CACHE_MIN_FREE      Start evicting when the cache disk drops below this.
# VFS_CACHE_POLL_INTERVAL How often the cleaner runs (rclone default is 1m).
VFS_CACHE_MAX_SIZE="${VFS_CACHE_MAX_SIZE:-5G}"
VFS_CACHE_MAX_AGE="${VFS_CACHE_MAX_AGE:-1h}"
VFS_CACHE_MIN_FREE="${VFS_CACHE_MIN_FREE:-5G}"
VFS_CACHE_POLL_INTERVAL="${VFS_CACHE_POLL_INTERVAL:-1m}"

# --- Upload throughput tuning ---
# DRIVE_CHUNK_SIZE  Upload chunk size. rclone's default is 8M, which stalls on
#                   high-latency links: each chunk is a separate HTTP request
#                   and the connection idles during the round trip. Larger
#                   chunks keep the pipe full. Costs RAM: chunk x transfers.
# TRANSFERS         Parallel uploads. Drive throttles per-stream, so a few
#                   concurrent transfers beat one fast one.
# DRIVE_PACER_MIN_SLEEP  Delay between API calls (rclone default 100ms).
DRIVE_CHUNK_SIZE="${DRIVE_CHUNK_SIZE:-64M}"
TRANSFERS="${TRANSFERS:-4}"
DRIVE_PACER_MIN_SLEEP="${DRIVE_PACER_MIN_SLEEP:-10ms}"
DRIVE_PACER_BURST="${DRIVE_PACER_BURST:-200}"

do_unmount() {
    echo ""
    echo "=== Unmount Options ==="
    echo "1) Stop mount service temporarily (systemctl --user stop)"
    echo "2) Stop AND disable auto-start on boot (systemctl --user disable --now)"
    echo "3) Force / Lazy unmount immediately (fusermount -u -z)"
    echo "4) Cancel"
    read -p "Select an option [1-4]: " UNMOUNT_CHOICE

    case "$UNMOUNT_CHOICE" in
        1)
            echo "[+] Stopping ${SERVICE_NAME}.service..."
            systemctl --user stop "${SERVICE_NAME}.service" || true
            echo "[✓] Mount service stopped successfully."
            ;;
        2)
            echo "[+] Stopping and disabling ${SERVICE_NAME}.service..."
            systemctl --user disable --now "${SERVICE_NAME}.service" || true
            echo "[✓] Mount service stopped and disabled."
            ;;
        3)
            echo "[+] Force unmounting ${MOUNT_DIR}..."
            systemctl --user stop "${SERVICE_NAME}.service" 2>/dev/null || true
            fusermount -u -z "${MOUNT_DIR}" 2>/dev/null || true
            echo "[✓] Force unmount executed."
            ;;
        4)
            echo "Operation cancelled."
            exit 0
            ;;
        *)
            echo "Invalid selection."
            exit 1
            ;;
    esac
}

do_status() {
    echo ""
    echo "=== Mount Status ==="
    systemctl --user status "${SERVICE_NAME}.service" --no-pager || true
    echo ""
    if mountpoint -q "${MOUNT_DIR}"; then
        echo "[✓] Mount point '${MOUNT_DIR}' is ACTIVE."
    else
        echo "[!] Mount point '${MOUNT_DIR}' is NOT mounted."
    fi
}

# Emit a standalone start/stop/status script that runs the same rclone
# command as the systemd unit, for hosts where systemd is unavailable.
write_runner_script() {
    mkdir -p "$(dirname "$RUNNER_SCRIPT")"
    cat > "$RUNNER_SCRIPT" <<RUNNER
#!/usr/bin/env bash
# Generated by setup_gdrive_mount.sh - runs the rclone mount without systemd.
set -u

MOUNT_DIR="${MOUNT_DIR}"
CACHE_DIR="${CACHE_DIR}"
PIDFILE="${PIDFILE}"
RCLONE_BIN="${RCLONE_BIN}"
FUSERMOUNT_BIN="${FUSERMOUNT_BIN}"
LOG="${CACHE_DIR}/rclone.log"
# rclone writes fatal startup errors (FUSE denied, bad flag, missing config)
# to stderr and exits BEFORE --log-file is ever opened, so those never reach
# \$LOG. Capture stderr separately or the failure is invisible.
STARTUP_LOG="${CACHE_DIR}/rclone-startup.log"

is_running() {
    [ -f "\$PIDFILE" ] || return 1
    kill -0 "\$(cat "\$PIDFILE" 2>/dev/null)" 2>/dev/null
}

case "\${1:-}" in
  start)
    if is_running; then
        echo "[i] Already running (PID \$(cat "\$PIDFILE"))."
        exit 0
    fi
    mkdir -p "\$MOUNT_DIR" "\$CACHE_DIR"
    # Clear any stale endpoint from a previous crash
    "\$FUSERMOUNT_BIN" -u -z "\$MOUNT_DIR" 2>/dev/null || true

    # Preflight: prove FUSE actually works before blaming rclone. In a
    # container this is the usual failure, and the kernel error is far
    # clearer than anything rclone reports.
    if [ ! -e /dev/fuse ]; then
        echo "[X] /dev/fuse does not exist inside this container."
        echo "    Add to docker-compose.yml:  devices: [\"/dev/fuse:/dev/fuse\"]"
        echo "    and load it on the HOST:    sudo modprobe fuse"
        exit 1
    fi
    if [ ! -r /dev/fuse ] || [ ! -w /dev/fuse ]; then
        echo "[X] /dev/fuse exists but is not readable/writable by \$(id -un)."
        echo "    \$(ls -l /dev/fuse)"
        echo "    Fix: add the user to the 'fuse' group, or run privileged."
        exit 1
    fi
    echo "[+] Starting rclone mount..."
    : > "\$STARTUP_LOG"
    nohup "\$RCLONE_BIN" mount ${REMOTE_NAME}: "\$MOUNT_DIR" \\
        --config ${RCLONE_CONF} \\
        --cache-dir "\$CACHE_DIR" \\
        --vfs-cache-mode full \\
        --vfs-cache-max-size ${VFS_CACHE_MAX_SIZE} \\
        --vfs-cache-max-age ${VFS_CACHE_MAX_AGE} \\
        --vfs-cache-poll-interval ${VFS_CACHE_POLL_INTERVAL} \\
        --allow-other \\
        --poll-interval 1m \\
        --dir-cache-time 1000h \\
        --attr-timeout 1000h \\
        --vfs-read-chunk-size 32M \\
        --vfs-read-chunk-size-limit 1G \\
        --buffer-size 32M \\
        --transfers ${TRANSFERS} \\
$(printf "${OPT_FLAGS_RUNNER}")
        --log-file "\$LOG" \\
        --log-level INFO${MOUNT_FLAGS} >>"\$STARTUP_LOG" 2>&1 &
    echo \$! > "\$PIDFILE"
    sleep 3
    if is_running && mountpoint -q "\$MOUNT_DIR" 2>/dev/null; then
        echo "[✓] Started (PID \$(cat "\$PIDFILE")). Mount: \$MOUNT_DIR"
    elif is_running; then
        echo "[!] Process is alive but \$MOUNT_DIR is not mounted yet."
        echo "    Give it a few seconds, then: \$0 status"
    else
        echo "[X] Failed to start."
        echo ""
        echo "--- rclone startup error (stderr) ---"
        if [ -s "\$STARTUP_LOG" ]; then
            sed 's/^/    /' "\$STARTUP_LOG"
        else
            echo "    (nothing on stderr)"
        fi
        if [ -s "\$LOG" ]; then
            echo "--- last log lines ---"
            tail -n 10 "\$LOG" 2>/dev/null | sed 's/^/    /'
        fi
        echo ""
        # Decode the usual container failures into a concrete fix.
        ERRTXT=\$(cat "\$STARTUP_LOG" 2>/dev/null)
        if echo "\$ERRTXT" | grep -qi "operation not permitted\|permission denied"; then
            echo "    => The kernel refused the FUSE mount."
            echo "       Host:      sudo modprobe fuse"
            echo "       Compose:   devices: [\"/dev/fuse:/dev/fuse\"]"
            echo "                  security_opt: [apparmor:unconfined]"
            echo "       Then recreate: docker compose down && docker compose up -d"
        elif echo "\$ERRTXT" | grep -qi "fusermount.*not found\|no such file"; then
            echo "    => fusermount is missing inside the container."
            echo "       Install it: sudo apt-get update && sudo apt-get install -y fuse3"
        elif echo "\$ERRTXT" | grep -qi "unknown flag\|unknown command"; then
            echo "    => This rclone build does not support one of the flags above."
            echo "       Upgrade it: sudo -v ; curl https://rclone.org/install.sh | sudo bash"
        elif echo "\$ERRTXT" | grep -qi "didn't find section\|couldn't find section"; then
            echo "    => The remote '${REMOTE_NAME}' is missing from the rclone config."
        elif echo "\$ERRTXT" | grep -qi "directory is not empty\|mountpoint"; then
            echo "    => Mountpoint busy or not empty:"
            echo "       \$FUSERMOUNT_BIN -u -z \$MOUNT_DIR"
        fi
        rm -f "\$PIDFILE"
        exit 1
    fi
    ;;
  stop)
    if is_running; then
        kill "\$(cat "\$PIDFILE")" 2>/dev/null || true
        sleep 2
    fi
    "\$FUSERMOUNT_BIN" -u -z "\$MOUNT_DIR" 2>/dev/null || true
    rm -f "\$PIDFILE"
    echo "[✓] Stopped and unmounted."
    ;;
  status)
    if is_running; then
        echo "[✓] Running (PID \$(cat "\$PIDFILE"))"
    else
        echo "[!] Not running"
    fi
    if mountpoint -q "\$MOUNT_DIR" 2>/dev/null; then
        echo "[✓] \$MOUNT_DIR is mounted"
    else
        echo "[!] \$MOUNT_DIR is NOT mounted"
    fi
    ;;
  restart)
    "\$0" stop; sleep 1; "\$0" start
    ;;
  *)
    echo "Usage: \$0 {start|stop|restart|status}"
    exit 1
    ;;
esac
RUNNER
    chmod +x "$RUNNER_SCRIPT"
}

do_doctor() {
    echo ""
    echo "=========================================================="
    echo "  Mount Startup Diagnosis"
    echo "=========================================================="
    PROBLEMS=0

    # --- 0. Is systemd even usable here? ---------------------------
    if ! have_systemd; then
        echo ""
        echo "--- 0. Init system ---"
        echo "    [!] systemd is NOT available (container / WSL / chroot)."
        echo "        systemctl --user cannot work here, so the unit file is"
        echo "        inert. Use the standalone runner instead:"
        echo "          ${RUNNER_SCRIPT} {start|stop|restart|status}"
        if [ ! -x "$RUNNER_SCRIPT" ]; then
            echo "        Not created yet - run: ./setup_gdrive_mount.sh setup"
        fi
        echo ""
        echo "        FUSE inside a container also needs the host to permit it:"
        echo "          docker run --cap-add SYS_ADMIN --device /dev/fuse \\"
        echo "                     --security-opt apparmor:unconfined ..."
        echo "        Checking /dev/fuse below will confirm."
    fi

    # --- 1. Is rclone where the unit expects it? -------------------
    echo ""
    echo "--- 1. rclone binary ---"
    UNIT_FILE="${SYSTEMD_USER_DIR}/${SERVICE_NAME}.service"
    EXEC_BIN=$(grep -oE "^ExecStart=[^ ]+" "$UNIT_FILE" 2>/dev/null | cut -d= -f2) || EXEC_BIN=""
    REAL_BIN=$(command -v rclone 2>/dev/null) || REAL_BIN=""
    echo "    Unit expects : ${EXEC_BIN:-<no unit file>}"
    echo "    Actually at  : ${REAL_BIN:-<not on PATH>}"
    if [ -n "$EXEC_BIN" ] && [ ! -x "$EXEC_BIN" ]; then
        echo "    [X] ${EXEC_BIN} is missing or not executable."
        [ -n "$REAL_BIN" ] && echo "        Fix: re-run ./setup_gdrive_mount.sh setup (picks up ${REAL_BIN})"
        PROBLEMS=$((PROBLEMS + 1))
    else
        echo "    [OK]"
    fi

    # --- 2. Config file and remote ---------------------------------
    echo ""
    echo "--- 2. Config and remote '${REMOTE_NAME}' ---"
    if [ ! -f "$RCLONE_CONF" ]; then
        echo "    [X] No config at ${RCLONE_CONF}"
        echo "        This alone makes rclone exit 1 immediately."
        echo "        Fix: copy it from the working machine:"
        echo "          scp olduser@oldhost:~/.config/rclone/rclone.conf ${RCLONE_CONF}"
        PROBLEMS=$((PROBLEMS + 1))
    elif ! grep -q "^\[${REMOTE_NAME}\]" "$RCLONE_CONF"; then
        echo "    [X] Config exists but has no [${REMOTE_NAME}] section."
        echo "        Remotes found: $(grep -oE '^\[[^]]+\]' "$RCLONE_CONF" | tr '\n' ' ')"
        echo "        The unit mounts '${REMOTE_NAME}:' - names must match."
        PROBLEMS=$((PROBLEMS + 1))
    else
        echo "    [OK] ${RCLONE_CONF} has [${REMOTE_NAME}]"
        if [ -n "$REAL_BIN" ]; then
            echo "    Testing remote access (5s)..."
            if timeout 15 rclone lsd "${REMOTE_NAME}:" --config "$RCLONE_CONF" \
                 --low-level-retries 1 --retries 1 >/dev/null 2>/tmp/.rc_err; then
                echo "    [OK] Remote responds."
            else
                echo "    [X] Cannot reach the remote:"
                sed 's/^/        /' /tmp/.rc_err | head -n 6
                echo "        A stale or unauthorised token exits 1 at startup."
                echo "        Fix: rclone config reconnect ${REMOTE_NAME}:"
                PROBLEMS=$((PROBLEMS + 1))
            fi
            rm -f /tmp/.rc_err
        fi
    fi

    # --- 3. FUSE availability --------------------------------------
    echo ""
    echo "--- 3. FUSE ---"
    if [ ! -e /dev/fuse ]; then
        echo "    [X] /dev/fuse missing - the kernel module is not loaded."
        echo "        Fix: sudo modprobe fuse"
        PROBLEMS=$((PROBLEMS + 1))
    else
        echo "    [OK] /dev/fuse present"
    fi
    if ! command -v fusermount3 &>/dev/null && ! command -v fusermount &>/dev/null; then
        echo "    [X] No fusermount/fusermount3 binary."
        echo "        Fix: sudo dnf install fuse3   (or apt install fuse3)"
        PROBLEMS=$((PROBLEMS + 1))
    else
        FUSEBIN=$(command -v fusermount3 2>/dev/null) || FUSEBIN=$(command -v fusermount 2>/dev/null) || FUSEBIN="?"
        echo "    [OK] ${FUSEBIN}"
        FUSERMOUNT_FIX="$FUSEBIN"
    fi

    # --allow-other requires user_allow_other in /etc/fuse.conf. This is
    # the classic "works on the old box, fails on the new one" difference,
    # because the old machine was configured months ago and forgotten.
    if grep -q -- "--allow-other" "$UNIT_FILE" 2>/dev/null; then
        if [ -f /etc/fuse.conf ] && grep -qE "^[[:space:]]*user_allow_other" /etc/fuse.conf; then
            echo "    [OK] user_allow_other enabled (needed by --allow-other)"
        else
            echo "    [X] The unit uses --allow-other but /etc/fuse.conf does NOT"
            echo "        have user_allow_other. rclone exits 1 immediately."
            echo "        Fix: echo user_allow_other | sudo tee -a /etc/fuse.conf"
            echo "        (or drop --allow-other from the unit)"
            PROBLEMS=$((PROBLEMS + 1))
        fi
    fi

    # ExecStop/ExecStartPre must point at a binary that exists. fuse3-only
    # distros (Arch) have no /bin/fusermount, so a unit generated elsewhere
    # fails to clean up, leaving a stale mount that blocks every restart.
    for LINE in ExecStop ExecStartPre; do
        UBIN=$(grep -oE "^${LINE}=-?[^ ]+" "$UNIT_FILE" 2>/dev/null | head -n1 | sed -E "s/^${LINE}=-?//") || UBIN=""
        if [ -n "$UBIN" ] && [ ! -x "$UBIN" ]; then
            echo "    [X] ${LINE} points at ${UBIN}, which does not exist."
            echo "        Unmount-on-stop cannot run, so a failed start leaves a"
            echo "        stale mount that blocks every retry (restart loop)."
            echo "        Fix: re-run ./setup_gdrive_mount.sh setup"
            PROBLEMS=$((PROBLEMS + 1))
        fi
    done

    if ! grep -q "^ExecStartPre=" "$UNIT_FILE" 2>/dev/null; then
        echo "    [!] Unit has no ExecStartPre cleanup. If a start ever fails"
        echo "        mid-mount, the leftover endpoint blocks all retries."
        echo "        Fix: re-run ./setup_gdrive_mount.sh setup"
    fi

    # --- 4. Mountpoint ---------------------------------------------
    echo ""
    echo "--- 4. Mountpoint ${MOUNT_DIR} ---"
    if mountpoint -q "$MOUNT_DIR" 2>/dev/null; then
        if systemctl --user is-active --quiet "${SERVICE_NAME}.service" 2>/dev/null; then
            echo "    [OK] Mounted and the service is running."
        else
            echo "    [X] STALE MOUNT: mounted, but the service is NOT running."
            echo "        This is the classic restart loop: rclone cannot mount"
            echo "        over a live endpoint, so every retry exits 1."
            echo "        Fix:"
            echo "          systemctl --user stop ${SERVICE_NAME}.service"
            echo "          ${FUSERMOUNT_FIX:-fusermount3} -u -z ${MOUNT_DIR}"
            echo "          systemctl --user start ${SERVICE_NAME}.service"
            PROBLEMS=$((PROBLEMS + 1))
        fi
    elif [ ! -d "$MOUNT_DIR" ]; then
        echo "    [X] Does not exist. Fix: mkdir -p ${MOUNT_DIR}"
        PROBLEMS=$((PROBLEMS + 1))
    elif [ -n "$(ls -A "$MOUNT_DIR" 2>/dev/null)" ]; then
        echo "    [!] Not empty - rclone refuses to mount over existing files:"
        ls -A "$MOUNT_DIR" | head -n 5 | sed 's/^/        /'
        PROBLEMS=$((PROBLEMS + 1))
    else
        echo "    [OK] exists and is empty"
    fi

    # --- 5. The actual error ---------------------------------------
    echo ""
    echo "--- 5. rclone's own error output ---"
    echo "    systemd only reports 'status=1'; the real message goes to"
    echo "    the log file. Most recent errors:"
    if [ -f "${CACHE_DIR}/rclone.log" ]; then
        ERRS=$(grep -iE "error|fatal|failed|cannot|denied" "${CACHE_DIR}/rclone.log" 2>/dev/null | tail -n 8)
        if [ -n "$ERRS" ]; then
            echo "$ERRS" | sed 's/^/      /'
        else
            echo "      (none logged - rclone may be failing before it opens the log)"
        fi
    else
        echo "      (no log file - rclone is failing before it can create one,"
        echo "       which points at a bad flag, missing config, or FUSE issue)"
    fi
    echo ""
    echo "    To see the error directly, run the mount in the foreground:"
    echo "        ./setup_gdrive_mount.sh trymount"

    echo ""
    echo "=========================================================="
    if [ "$PROBLEMS" -eq 0 ]; then
        echo "  No blocking problems found - run 'trymount' to see the error."
    else
        echo "  ${PROBLEMS} problem(s) found above."
    fi
    echo "=========================================================="
    echo ""
}

do_trymount() {
    echo ""
    echo "=== Foreground Mount Test ==="
    echo "Runs the unit's exact command WITHOUT --log-file, so rclone's error"
    echo "prints here instead of disappearing into the log. Ctrl-C to stop."
    echo ""

    UNIT_FILE="${SYSTEMD_USER_DIR}/${SERVICE_NAME}.service"
    if [ ! -f "$UNIT_FILE" ]; then
        echo "[!] No unit at ${UNIT_FILE}. Run setup first."
        return 1
    fi

    if systemctl --user is-active --quiet "${SERVICE_NAME}.service"; then
        echo "[!] Service is running; stop it first:"
        echo "      systemctl --user stop ${SERVICE_NAME}.service"
        return 1
    fi

    # Rebuild the ExecStart line: join continuations, drop the systemd
    # prefix, expand %h, and strip --log-file so output comes to the
    # terminal. Add -vv for the full reason.
    CMD=$(sed -n '/^ExecStart=/,/[^\\]$/p' "$UNIT_FILE" \
          | tr '\n' ' ' | sed 's/\\ / /g; s/^ExecStart=//' \
          | sed "s|%h|${HOME}|g" \
          | sed -E 's/--log-file[= ][^ ]+//; s/--log-level[= ][^ ]+//')

    echo "Running:"
    echo "  ${CMD} -vv"
    echo ""
    echo "--- rclone output ---"
    # shellcheck disable=SC2086
    timeout 25 $CMD -vv 2>&1 | tail -n 40
    RC=${PIPESTATUS[0]}
    echo "--- exit ${RC} ---"
    if [ "$RC" -eq 124 ]; then
        echo ""
        echo "[OK] It ran for 25s without exiting - the mount itself works."
        echo "     Unmount with: fusermount -u -z ${MOUNT_DIR}"
    fi
}

do_reupload() {
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"
    DRY=false
    [ "$1" = "--dry-run" ] && DRY=true

    echo ""
    echo "=========================================================="
    echo "  Re-upload Pending Files Directly"
    echo "=========================================================="
    echo ""
    echo "Use this when rclone's writeback queue is empty ('to upload 0')"
    echo "but files on disk are still dirty - the VFS will never retry them,"
    echo "so we push them to Drive with 'rclone copy' instead."
    echo ""

    if [ ! -d "$VFS_META_DIR" ]; then
        echo "[i] No cache metadata; nothing to do."
        return 0
    fi

    # The cache mirrors the remote layout under vfs/<remote>/<path>, so the
    # path after the remote name is exactly the destination path on Drive.
    ROOT_DIR="${VFS_DIR}/${REMOTE_NAME}"
    if [ ! -d "$ROOT_DIR" ]; then
        echo "[!] Expected cache root ${ROOT_DIR} does not exist."
        echo "    Cache layout may differ; listing what is there:"
        ls -1 "$VFS_DIR" 2>/dev/null | sed 's/^/      /'
        return 1
    fi

    LIST=$(mktemp)
    COUNT=0
    BYTES=0
    while IFS= read -r META; do
        grep -q '"Dirty": true' "$META" 2>/dev/null || continue
        REL="${META#"$VFS_META_DIR"/}"          # e.g. gdrive/Lib/foo.bin
        SRC="${VFS_DIR}/${REL}"
        [ -f "$SRC" ] || continue
        DEST_PATH="${REL#"${REMOTE_NAME}/"}"    # strip remote name -> Lib/foo.bin
        printf '%s\t%s\n' "$SRC" "$DEST_PATH" >> "$LIST"
        BYTES=$((BYTES + $(( $(stat -c %b "$SRC" 2>/dev/null || echo 0) * 512 )) ))
        COUNT=$((COUNT + 1))
    done < <(find "$VFS_META_DIR" -type f 2>/dev/null)

    if [ "$COUNT" -eq 0 ]; then
        echo "[i] No dirty files found - nothing pending."
        rm -f "$LIST"
        return 0
    fi

    echo "Found ${COUNT} pending file(s), $(numfmt --to=iec --suffix=B "$BYTES" 2>/dev/null || echo "$BYTES")."
    echo ""
    echo "First few destinations on ${REMOTE_NAME}:"
    head -n 5 "$LIST" | while IFS=$'\t' read -r s d; do echo "    ${d}"; done
    [ "$COUNT" -gt 5 ] && echo "    ... and $((COUNT - 5)) more"
    echo ""

    if [ "$DRY" = true ]; then
        echo "[dry-run] No changes made. Re-run without --dry-run to upload."
        rm -f "$LIST"
        return 0
    fi

    echo "[!] This uploads from the cache to Drive. It does NOT delete anything."
    read -p "Proceed? (y/N): " OK
    if [[ ! "$OK" =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        rm -f "$LIST"
        return 0
    fi

    OKN=0
    FAILN=0
    FAILED_LIST=()
    while IFS=$'\t' read -r SRC DEST_PATH; do
        DEST_DIR=$(dirname "$DEST_PATH")
        [ "$DEST_DIR" = "." ] && DEST_DIR=""
        echo "  -> ${DEST_PATH}"
        # NB: piping to sed would mask rclone's exit status (the pipeline
        # returns sed's status), silently counting failed uploads as
        # successes and inviting a destructive clear-cache afterwards.
        # Capture output, then test rclone's own status.
        # `|| CP_RC=$?` keeps `set -e` from aborting the whole run on the
        # first failed file; we want to attempt every file and report.
        CP_RC=0
        CP_OUT=$(rclone copyto "$SRC" "${REMOTE_NAME}:${DEST_PATH}" \
              --config "$RCLONE_CONF" \
              --drive-chunk-size "$DRIVE_CHUNK_SIZE" \
              --transfers 1 --stats 10s --stats-one-line 2>&1) || CP_RC=$?
        [ -n "$CP_OUT" ] && printf '%s\n' "$CP_OUT" | sed 's/^/     /'
        if [ "$CP_RC" -eq 0 ]; then
            OKN=$((OKN + 1))
        else
            FAILN=$((FAILN + 1))
            FAILED_LIST+=("$DEST_PATH")
            echo "     [!] FAILED (rclone exit ${CP_RC})"
        fi
    done < "$LIST"
    rm -f "$LIST"

    echo ""
    if [ "$FAILN" -gt 0 ]; then
        echo "  ######################################################"
        echo "  #  ${FAILN} UPLOAD(S) FAILED - DO NOT CLEAR THE CACHE      "
        echo "  ######################################################"
        echo ""
        echo "  Uploaded ${OKN}, FAILED ${FAILN}."
        echo ""
        echo "  These files did NOT reach Drive and exist only in the cache:"
        printf '    %s\n' "${FAILED_LIST[@]}" | head -n 20
        [ "${#FAILED_LIST[@]}" -gt 20 ] && echo "    ... and $((${#FAILED_LIST[@]} - 20)) more"
        echo ""
        echo "  Diagnose before retrying:  ./setup_gdrive_mount.sh uploads"
        echo "  Back them up:              ./setup_gdrive_mount.sh rescue-pending ~/drive-backup"
        return 1
    fi

    echo "[✓] Uploaded ${OKN}, failed 0."
    echo ""
    echo "    Verify a few on Drive, then clear the stale cache entries:"
    echo "        systemctl --user stop ${SERVICE_NAME}.service"
    echo "        ./setup_gdrive_mount.sh clear-cache --force"
    echo "        systemctl --user start ${SERVICE_NAME}.service"
}

do_logtail() {
    LOG="${CACHE_DIR}/rclone.log"

    echo ""
    echo "=========================================================="
    echo "  Raw Mount Activity"
    echo "=========================================================="

    if [ ! -f "$LOG" ]; then
        echo "[!] No log at ${LOG}"
        return 1
    fi

    echo ""
    echo "--- Log freshness ---"
    echo "    Last written: $(date -r "$LOG" '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"
    echo "    Now:          $(date '+%Y-%m-%d %H:%M:%S')"
    echo "    Size:         $(du -h "$LOG" 2>/dev/null | cut -f1)"

    # ---------------------------------------------------------------
    # The cleaner stats line is authoritative: it reports how many
    # items rclone itself thinks are queued and uploading. If these
    # are 0 while files are dirty on disk, rclone is not even trying.
    # ---------------------------------------------------------------
    echo ""
    echo "--- rclone's own writeback queue (last 5 cleaner runs) ---"
    CLEAN=$(grep "vfs cache: cleaned:" "$LOG" 2>/dev/null | tail -n 5)
    if [ -z "$CLEAN" ]; then
        echo "    (none yet - the cleaner logs once per --vfs-cache-poll-interval)"
    else
        echo "$CLEAN" | sed 's/.*vfs cache: cleaned: /    /'
        echo ""
        LAST=$(echo "$CLEAN" | tail -n1)
        TOUP=$(echo "$LAST"  | grep -oE "to upload [0-9]+"  | grep -oE "[0-9]+")
        UPING=$(echo "$LAST" | grep -oE "uploading [0-9]+"  | grep -oE "[0-9]+")
        # Actually count dirty files rather than asserting they exist: an
        # idle queue is entirely normal when nothing is pending.
        DIRTY_ON_DISK=0
        if [ -d "${CACHE_DIR}/vfsMeta" ]; then
            while IFS= read -r M; do
                grep -q '"Dirty": true' "$M" 2>/dev/null && DIRTY_ON_DISK=$((DIRTY_ON_DISK + 1))
            done < <(find "${CACHE_DIR}/vfsMeta" -type f 2>/dev/null)
        fi

        if [ "${TOUP:-0}" -eq 0 ] && [ "${UPING:-0}" -eq 0 ] && [ "$DIRTY_ON_DISK" -gt 0 ] 2>/dev/null; then
            echo "    [!!] rclone reports NOTHING queued and NOTHING uploading,"
            echo "         yet ${DIRTY_ON_DISK} file(s) on disk are still marked dirty."
            echo ""
            echo "         That means the writeback queue is empty - rclone is"
            echo "         not retrying these files at all. Usually the mount"
            echo "         was restarted before it re-queued them, or the files"
            echo "         are held open by an application so writeback is"
            echo "         deferred until the last handle closes."
            echo ""
            echo "         Fix: close anything using the mount, then restart:"
            echo "           systemctl --user restart ${SERVICE_NAME}.service"
            echo "         If that does not re-queue them, upload directly:"
            echo "           ./setup_gdrive_mount.sh reupload --dry-run"
        elif [ "${TOUP:-0}" -eq 0 ] && [ "${UPING:-0}" -eq 0 ]; then
            echo "    [OK] Queue is empty and no files are dirty - nothing pending."
        else
            echo "    [OK] rclone has ${TOUP:-?} queued, ${UPING:-?} uploading right now."
        fi
    fi

    echo ""
    echo "--- Transfer stats lines (from --stats) ---"
    # Match both stats formats: "Transferred: ..." (multi-line) and the
    # bare "1.2 GiB / 33 GiB, 3%, ..." emitted by --stats-one-line, which
    # this unit enables.
    ST=$(grep -E "Transferred:|[0-9.]+ *[KMGT]?i?B? */ +[0-9.]+ *[KMGT]?i?B" "$LOG" 2>/dev/null | tail -n 5)
    if [ -z "$ST" ]; then
        echo "    (none - either --stats is not enabled on the RUNNING process,"
        echo "     or nothing has transferred since it started)"
        echo ""
        echo "    Check the running process actually has it:"
        echo "        tr '\\0' '\\n' < /proc/\$(pgrep -f 'rclone mount' | head -1)/cmdline | grep stats"
    else
        echo "$ST" | sed 's/^/    /'
    fi

    echo ""
    echo "--- Last 20 vfs cache events ---"
    VE=$(grep -iE "vfs cache" "$LOG" 2>/dev/null | grep -viE "vfs cache: cleaned:" | tail -n 20)
    if [ -z "$VE" ]; then
        echo "    (no vfs cache events logged)"
    else
        echo "$VE" | sed 's/^/    /'
    fi

    echo ""
    echo "--- Last 15 lines of the log (anything at all) ---"
    tail -n 15 "$LOG" | sed 's/^/    /'
    echo ""
}

do_watch() {
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"

    # Count dirty (pending upload) items and their real disk bytes.
    _pending() {
        local n=0 b=0 meta rel src
        [ -d "$VFS_META_DIR" ] || { echo "0 0"; return; }
        while IFS= read -r meta; do
            grep -q '"Dirty": true' "$meta" 2>/dev/null || continue
            rel="${meta#"$VFS_META_DIR"/}"
            src="${VFS_DIR}/${rel}"
            [ -f "$src" ] || continue
            b=$((b + $(( $(stat -c %b "$src" 2>/dev/null || echo 0) * 512 )) ))
            n=$((n + 1))
        done < <(find "$VFS_META_DIR" -type f 2>/dev/null)
        echo "$n $b"
    }

    _fmt() { numfmt --to=iec --suffix=B "$1" 2>/dev/null || echo "$1"; }

    # Bytes rclone has actually sent, from the --stats line. The dirty-file
    # count only changes when a whole file completes, so on multi-hundred-MB
    # files it can sit unchanged for many minutes while transfer is healthy.
    # This is the real liveness signal.
    _sent() {
        local log="${CACHE_DIR}/rclone.log" line val unit
        [ -f "$log" ] || { echo ""; return; }
        # Two formats, depending on --stats-one-line:
        #   multi-line: "Transferred:   1.234 GiB / 33 GiB, 3%, 12.3 MiB/s, ETA 40m"
        #   one-line:   "1.234 GiB / 33 GiB, 3%, 12.3 MiB/s, ETA 40m"  (no prefix)
        # Match the "<num> <unit> /" shape common to both, after stripping any
        # leading timestamp/level so the date digits are never picked up.
        line=$(grep -E "[0-9.]+ *[KMGTi]*B? */ " "$log" 2>/dev/null \
               | sed -E 's/^[0-9\/]+ [0-9:]+[[:space:]]+[A-Z]+[[:space:]]+:[[:space:]]*//; s/^.*Transferred:[[:space:]]*//; s/^[[:space:]]+//' \
               | grep -oE "^[0-9.]+ *[KMGT]?i?B" | tail -n1)
        [ -n "$line" ] || { echo ""; return; }
        val=$(echo "$line" | grep -oE "[0-9.]+" | head -n1)
        unit=$(echo "$line" | grep -oiE "[KMGT]i?B" | head -n1)
        case "${unit^^}" in
            KIB|KB) awk -v v="$val" 'BEGIN{printf "%.0f", v*1024}' ;;
            MIB|MB) awk -v v="$val" 'BEGIN{printf "%.0f", v*1048576}' ;;
            GIB|GB) awk -v v="$val" 'BEGIN{printf "%.0f", v*1073741824}' ;;
            TIB|TB) awk -v v="$val" 'BEGIN{printf "%.0f", v*1099511627776}' ;;
            *)      awk -v v="$val" 'BEGIN{printf "%.0f", v}' ;;
        esac
    }

    echo ""
    echo "=== Watching Upload Backlog (Ctrl-C to stop) ==="
    echo ""

    read -r START_N START_B < <(_pending)
    if [ "$START_N" -eq 0 ]; then
        echo "[✓] Nothing pending - everything has uploaded."
        return 0
    fi

    echo "Starting backlog: ${START_N} file(s), $(_fmt "$START_B")"
    echo ""
    printf '%-9s %8s %12s %12s %s\n' "TIME" "FILES" "REMAINING" "RATE" "ETA"

    START_T=$(date +%s)
    PREV_B=$START_B
    PREV_T=$START_T
    START_SENT=$(_sent)
    PREV_SENT=$START_SENT
    LAST_PROGRESS_T=$START_T

    while true; do
        sleep 30
        read -r N B < <(_pending)
        NOW=$(date +%s)
        SENT=$(_sent)

        DT=$((NOW - PREV_T))
        DB=$((PREV_B - B))
        RATE=0
        [ "$DT" -gt 0 ] && RATE=$((DB / DT))

        # Prefer live wire throughput when rclone is reporting it: it shows
        # progress within a file, not just on completion.
        WIRE=0
        DSENT=0
        if [ -n "$SENT" ] && [ -n "$PREV_SENT" ] && [ "$DT" -gt 0 ]; then
            DSENT=$((SENT - PREV_SENT))
            [ "$DSENT" -gt 0 ] && WIRE=$((DSENT / DT))
        fi
        [ "$WIRE" -gt 0 ] && RATE=$WIRE

        # Average rate over the whole window is steadier for ETA.
        TOT_DT=$((NOW - START_T))
        TOT_DB=$((START_B - B))
        AVG=0
        [ "$TOT_DT" -gt 0 ] && AVG=$((TOT_DB / TOT_DT))

        if [ "$AVG" -gt 0 ]; then
            ETA_S=$((B / AVG))
            ETA=$(printf '%dh%02dm' $((ETA_S / 3600)) $(((ETA_S % 3600) / 60)))
        else
            ETA="--"
        fi

        if [ "$RATE" -gt 0 ]; then
            RATE_S="$(_fmt "$RATE")/s"
        elif [ -n "$SENT" ]; then
            # rclone is reporting stats but no delta this interval.
            RATE_S="idle"
        else
            # No completions yet and no stats to read. Normal for big files.
            RATE_S="in-flight"
        fi

        printf '%-9s %8s %12s %12s %s\n' \
            "$(date +%H:%M:%S)" "$N" "$(_fmt "$B")" "$RATE_S" "$ETA"

        if [ "$N" -eq 0 ]; then
            echo ""
            echo "[✓] Backlog cleared - all files uploaded to Drive."
            echo "    The cache will now shrink to your --vfs-cache-max-size."
            return 0
        fi

        # Stall detection is based on time since the last OBSERVED progress,
        # not on cumulative totals from the start. Totals break when the log
        # only appears partway through (fresh mount): the baseline is empty,
        # so the delta stays 0 forever and a healthy upload is reported as
        # stalled. Any completion or any wire movement resets the clock.
        if [ "$DB" -gt 0 ] || [ "${DSENT:-0}" -gt 0 ]; then
            LAST_PROGRESS_T=$NOW
        fi
        STALL_FOR=$((NOW - LAST_PROGRESS_T))
        if [ "$STALL_FOR" -ge 900 ]; then
            echo ""
            echo "[!] No files completed and no bytes sent in $((STALL_FOR / 60)) minutes."
            echo "    Diagnose with: ./setup_gdrive_mount.sh uploads"
            echo "    If rclone reports 'to upload 0', its queue is empty:"
            echo "        ./setup_gdrive_mount.sh logtail"
            return 1
        fi

        PREV_B=$B
        PREV_T=$NOW
        PREV_SENT=$SENT
    done
}

do_speedcheck() {
    echo ""
    echo "=========================================================="
    echo "  Upload Throughput Check"
    echo "=========================================================="

    # ---------------------------------------------------------------
    # 1. Own client_id. Without one you share rclone's global OAuth
    #    client with every other rclone user, and Google's per-client
    #    rate limiting is what throttles you.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 1. OAuth client_id ---"
    if [ -f "$RCLONE_CONF" ] && \
       awk -v r="[${REMOTE_NAME}]" '$0==r{f=1;next} /^\[/{f=0} f' "$RCLONE_CONF" | grep -q "^client_id *= *[^ ]"; then
        echo "  [OK] Using your own client_id."
    else
        echo "  [!!] NO client_id - THIS IS USUALLY THE #1 CAUSE OF SLOW UPLOADS."
        echo ""
        echo "       You are sharing rclone's global OAuth client with every"
        echo "       other rclone user on the planet. Google rate-limits per"
        echo "       client, so you inherit everyone else's traffic."
        echo ""
        echo "       Creating your own is free and takes ~10 minutes:"
        echo "         https://rclone.org/drive/#making-your-own-client-id"
        echo "       Then: rclone config  ->  edit '${REMOTE_NAME}'  ->  set client_id/secret"
        echo "       Your existing files and token are unaffected."
    fi

    # ---------------------------------------------------------------
    # 2. Effective upload flags on the running process.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 2. Upload flags in effect ---"
    RCLONE_PID=$(pgrep -u "$(id -u)" -f "rclone mount" | head -n1)
    if [ -z "$RCLONE_PID" ]; then
        echo "  (no running mount)"
    else
        ARGS=$(tr '\0' ' ' < "/proc/${RCLONE_PID}/cmdline" 2>/dev/null)
        for F in --drive-chunk-size --drive-upload-cutoff --transfers --drive-pacer-min-sleep --bwlimit; do
            # Handle both "--flag value" and "--flag=value"; stripping the
            # flag and any =/space separator covers both without awk column
            # assumptions (which silently miss the = form).
            V=$(echo "$ARGS" | grep -oE -- "${F}[= ][^ ]+" | head -n1 | sed -E "s|^${F}[= ]||")
            if [ -n "$V" ]; then
                printf '    %-26s %s\n' "$F" "$V"
            else
                case "$F" in
                    --drive-chunk-size)     printf '    %-26s %s\n' "$F" "8M (default)  <-- too small, see below" ;;
                    --drive-upload-cutoff)  printf '    %-26s %s\n' "$F" "8M (default)" ;;
                    --transfers)            printf '    %-26s %s\n' "$F" "4 (default)" ;;
                    --drive-pacer-min-sleep) printf '    %-26s %s\n' "$F" "100ms (default)" ;;
                    --bwlimit)              printf '    %-26s %s\n' "$F" "unset (no cap - good)" ;;
                esac
            fi
        done

        if echo "$ARGS" | grep -q -- "--bwlimit"; then
            echo ""
            echo "  [!!] --bwlimit is set. This caps your speed directly."
        fi
    fi

    # ---------------------------------------------------------------
    # 3. Measured throughput from the log.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 3. Recent measured upload speed ---"
    LOG="${CACHE_DIR}/rclone.log"
    if [ -f "$LOG" ]; then
        # Modern rclone prints "12.345 MiB/s"; older builds used "MBytes/s".
        # Match both, and skip the all-zero lines an idle mount emits.
        SPEEDS=$(grep -oE "[0-9.]+ *[KMGT]?i?B(ytes)?/s" "$LOG" 2>/dev/null \
                 | grep -vE "^0 *B(ytes)?/s$" | tail -n 5)
        if [ -n "$SPEEDS" ]; then
            echo "$SPEEDS" | sed 's/^/    /'
        else
            echo "    (no transfer stats in log; add --stats 30s to see them)"
        fi
        # grep -c exits 1 on zero matches; `|| echo 0` would then append a
        # second line, making RL multi-line and breaking the -gt test.
        RL=$(grep -ciE "rateLimitExceeded|userRateLimitExceeded|429" "$LOG" 2>/dev/null) || RL=0
        echo ""
        echo "    Rate-limit responses in log: ${RL}"
        if [ "$RL" -gt 0 ] 2>/dev/null; then
            echo "    [!] Google is actively throttling you. An own client_id"
            echo "        (section 1) is the fix; raising --transfers will not help."
        fi
    else
        echo "    (no log file yet - it is created once the mount starts and"
        echo "     transfers begin. Re-run this in a minute or two.)"
    fi

    # ---------------------------------------------------------------
    # 4. Guidance
    # ---------------------------------------------------------------
    echo ""
    echo "--- 4. What actually moves the needle ---"
    echo "  Google Drive throttles each upload STREAM, so a single transfer"
    echo "  rarely saturates a fast line no matter how it is tuned. Throughput"
    echo "  comes from parallelism plus large chunks:"
    echo ""
    echo "    --drive-chunk-size 64M   bigger HTTP requests, fewer round trips"
    echo "    --transfers 4            parallel streams (total = chunk x transfers RAM)"
    echo "    --drive-pacer-min-sleep 10ms   less idle time between API calls"
    echo ""
    echo "  Apply by re-running setup (values are overridable):"
    echo "      DRIVE_CHUNK_SIZE=64M TRANSFERS=4 ./setup_gdrive_mount.sh setup"
    echo ""
    echo "  RAM cost: --drive-chunk-size x --transfers is buffered in memory."
    echo "  64M x 4 = 256MB. Do not set 1G x 8 on a small machine."
    echo ""
    echo "  Note: Drive's ~750GB/day upload cap is separate. Hitting it causes"
    echo "  errors, not slowness - check with: ./setup_gdrive_mount.sh uploads"
    echo ""
}

do_uploads() {
    LOG="${CACHE_DIR}/rclone.log"

    echo ""
    echo "=========================================================="
    echo "  Pending Upload Analysis"
    echo "=========================================================="

    # Live queue via the rc interface, if the mount was started with --rc.
    echo ""
    echo "--- Live upload queue ---"
    if command -v rclone &> /dev/null && rclone rc vfs/queue --json 2>/dev/null | head -c 1 | grep -q .; then
        rclone rc vfs/queue 2>/dev/null | head -n 40
    else
        echo "  (rclone rc unavailable - mount not started with --rc. Using log instead.)"
    fi

    if [ ! -f "$LOG" ]; then
        echo ""
        echo "[i] No log file at ${LOG} yet."
        echo "    It appears once the mount starts and begins transferring."
        echo ""
        # A missing log doesn't mean nothing is pending - check the cache.
        VFS_META_DIR="${CACHE_DIR}/vfsMeta"
        PN=0
        if [ -d "$VFS_META_DIR" ]; then
            while IFS= read -r M; do
                grep -q '"Dirty": true' "$M" 2>/dev/null && PN=$((PN + 1))
            done < <(find "$VFS_META_DIR" -type f 2>/dev/null)
        fi
        if [ "$PN" -gt 0 ]; then
            echo "    ${PN} file(s) are still pending upload. Track progress with:"
            echo "        ./setup_gdrive_mount.sh watch"
        else
            echo "    Nothing is pending upload."
        fi
        return 0
    fi

    # ---------------------------------------------------------------
    # Distinct upload errors, most recent first. This is the payload:
    # the actual reason Drive is rejecting the writes.
    # ---------------------------------------------------------------
    echo ""
    echo "--- Recent upload failures ---"
    FAILS=$(grep -iE "vfs cache: failed to (upload|transfer)|failed to copy|Post \"https" "$LOG" 2>/dev/null | tail -n 200)
    if [ -z "$FAILS" ]; then
        echo "  No upload failures logged."
        echo "  If files are still pending, uploads may simply be slow or queued"
        echo "  behind --transfers. Watch progress with:"
        echo "      tail -f ${LOG} | grep -i 'vfs cache'"
    else
        echo "$FAILS" | tail -n 8 | sed 's/^/    /'
        echo ""
        echo "  Most common error signatures found:"
        echo "$FAILS" \
            | grep -oiE "storageQuotaExceeded|quotaExceeded|userRateLimitExceeded|rateLimitExceeded|teamDriveFileLimitExceeded|invalid_grant|token expired|401|403|404|500|502|503|couldn't fetch token|no space left|permission denied|context deadline exceeded|connection reset" \
            | sort | uniq -c | sort -rn | head -n 8 | sed 's/^/    /'
    fi

    # ---------------------------------------------------------------
    # Map the signature to a cause + fix. Infinite retry means a
    # permanent error will never clear on its own.
    # ---------------------------------------------------------------
    echo ""
    echo "--- Diagnosis ---"
    MATCHED=0

    if echo "$FAILS" | grep -qi "storageQuotaExceeded"; then
        MATCHED=1
        echo "  [X] GOOGLE DRIVE IS FULL (storageQuotaExceeded)."
        echo "      This is permanent - rclone retries forever but can never"
        echo "      succeed. Free space in Drive (or buy more), then restart"
        echo "      the mount. Uploads resume automatically."
        echo "      Check usage:  rclone about gdrive:"
    fi

    if echo "$FAILS" | grep -qiE "userRateLimitExceeded|rateLimitExceeded"; then
        MATCHED=1
        echo "  [!] RATE / QUOTA LIMIT HIT."
        echo "      Google Drive caps uploads at ~750GB/day per account. Once"
        echo "      tripped it clears after ~24h. Reduce concurrency so the"
        echo "      backlog drains without re-tripping it:"
        echo "          --transfers 2 --tpslimit 8 --drive-pacer-min-sleep 100ms"
    fi

    if echo "$FAILS" | grep -qiE "invalid_grant|token expired|couldn't fetch token|401"; then
        MATCHED=1
        echo "  [X] OAUTH TOKEN EXPIRED OR REVOKED."
        echo "      Every upload will keep failing until you re-authorise:"
        echo "          rclone config reconnect ${REMOTE_NAME}:"
        echo "      Then restart the mount. Do NOT delete the cache first."
    fi

    # Only report a bare 403 if a more specific 403 cause (quota/rate) didn't
    # already match, otherwise it is just noise.
    if echo "$FAILS" | grep -qiE "403|permission denied" \
       && ! echo "$FAILS" | grep -qiE "storageQuotaExceeded|userRateLimitExceeded|rateLimitExceeded"; then
        MATCHED=1
        echo "  [!] PERMISSION DENIED (403)."
        echo "      The account may lack write access to the target folder,"
        echo "      or the file is owned by someone else. Verify with:"
        echo "          rclone lsd ${REMOTE_NAME}:"
    fi

    if echo "$FAILS" | grep -qi "no space left"; then
        MATCHED=1
        echo "  [X] LOCAL DISK FULL."
        echo "      rclone cannot stage uploads with a full disk, so the queue"
        echo "      is deadlocked. Free local space first - see 'Rescue' below."
    fi

    if [ "$MATCHED" -eq 0 ] && [ -n "$FAILS" ]; then
        echo "  Errors present but unrecognised. Full context:"
        echo "      grep -i 'vfs cache' ${LOG} | tail -50"
    fi

    # ---------------------------------------------------------------
    # Always tell the user how to protect the data.
    # ---------------------------------------------------------------
    echo ""
    echo "--- Protecting the pending data ---"
    echo "  These 35GB-style backlogs exist ONLY in the cache. Before any"
    echo "  troubleshooting that risks the cache, copy them somewhere safe:"
    echo "      ./setup_gdrive_mount.sh rescue-pending /path/to/backup"
    echo ""
    echo "  rclone retries failed uploads forever (5 min max backoff), so a"
    echo "  permanent error like a full Drive will never resolve by waiting."
    echo ""
}

do_rescue_pending() {
    DEST="$1"
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"

    echo ""
    echo "=== Rescue Pending Uploads ==="

    if [ -z "$DEST" ]; then
        echo "Copies every not-yet-uploaded file out of the cache to a normal"
        echo "directory, so the data survives regardless of what happens next."
        echo ""
        echo "Usage: ./setup_gdrive_mount.sh rescue-pending /path/to/backup"
        return 1
    fi

    if [ ! -d "$VFS_META_DIR" ]; then
        echo "[i] No cache metadata directory; nothing pending."
        return 0
    fi

    mkdir -p "$DEST" || { echo "[!] Cannot create ${DEST}"; return 1; }

    COUNT=0
    BYTES=0
    while IFS= read -r META; do
        grep -q '"Dirty": true' "$META" 2>/dev/null || continue
        REL="${META#"$VFS_META_DIR"/}"
        SRC="${VFS_DIR}/${REL}"
        [ -f "$SRC" ] || continue
        mkdir -p "${DEST}/$(dirname "$REL")"
        # --sparse keeps holes; dirty files are normally fully written anyway.
        if cp --sparse=always --preserve=timestamps "$SRC" "${DEST}/${REL}" 2>/dev/null; then
            B=$(( $(stat -c %b "$SRC" 2>/dev/null || echo 0) * 512 ))
            BYTES=$((BYTES + B))
            COUNT=$((COUNT + 1))
            printf '    %8s  %s\n' \
                "$(numfmt --to=iec --suffix=B "$B" 2>/dev/null || echo "$B")" "$REL"
        else
            echo "    [!] FAILED to copy ${REL}"
        fi
    done < <(find "$VFS_META_DIR" -type f 2>/dev/null)

    echo ""
    if [ "$COUNT" -eq 0 ]; then
        echo "[i] No pending files found - everything has uploaded."
    else
        echo "[✓] Rescued ${COUNT} file(s), $(numfmt --to=iec --suffix=B "$BYTES" 2>/dev/null || echo "$BYTES") to ${DEST}"
        echo ""
        echo "    Verify the copies look right, then you can re-upload later with:"
        echo "        rclone copy ${DEST} ${REMOTE_NAME}:/ --progress"
        echo ""
        echo "    Keep this backup until the files are confirmed on Drive."
    fi
}

do_diagnose() {
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"

    echo ""
    echo "=========================================================="
    echo "  VFS Cache Diagnosis"
    echo "=========================================================="

    if [ ! -d "$VFS_DIR" ]; then
        echo "[i] No VFS cache directory at ${VFS_DIR}."
        return 0
    fi

    REAL_KB=$(du -sk "$VFS_DIR" 2>/dev/null | cut -f1)
    REAL_H=$(du -sh "$VFS_DIR" 2>/dev/null | cut -f1)
    echo ""
    echo "Real disk used: ${REAL_H}"

    # ---------------------------------------------------------------
    # 1. What flags is the RUNNING process actually using?
    #    A unit file edited but never reloaded/restarted is the single
    #    most common reason limits appear to be ignored.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 1. Flags of the RUNNING rclone process ---"
    RCLONE_PID=$(pgrep -u "$(id -u)" -f "rclone mount" | head -n1)
    if [ -z "$RCLONE_PID" ]; then
        echo "  [!] No running 'rclone mount' process found for this user."
        echo "      A stopped mount cannot evict anything, so the cache just sits there."
    else
        echo "  PID: ${RCLONE_PID}  (started: $(ps -o lstart= -p "$RCLONE_PID" 2>/dev/null | xargs))"
        RUNNING_ARGS=$(tr '\0' '\n' < "/proc/${RCLONE_PID}/cmdline" 2>/dev/null | tr '\n' ' ')
        for FLAG in --vfs-cache-max-size --vfs-cache-max-age --vfs-cache-min-free-space --vfs-cache-poll-interval --cache-dir; do
            # Handles both "--flag value" and "--flag=value" forms.
            VAL=$(echo "$RUNNING_ARGS" | grep -oE -- "${FLAG}[= ][^ ]+" | head -n1 | sed -E "s|^${FLAG}[= ]||")
            if [ -n "$VAL" ]; then
                printf '    %-28s %s\n' "$FLAG" "$VAL"
            else
                printf '    %-28s %s\n' "$FLAG" "NOT SET  <-- unbounded!"
            fi
        done
        echo ""
        echo "  If these differ from your unit file, the service was never restarted:"
        echo "      systemctl --user daemon-reload && systemctl --user restart ${SERVICE_NAME}.service"
    fi

    # ---------------------------------------------------------------
    # 2. Dirty items: pending upload. These are NEVER evicted, by
    #    design, and deleting them loses data.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 2. Dirty items (pending upload, NEVER evicted) ---"
    DIRTY_COUNT=0
    DIRTY_BYTES=0
    if [ -d "$VFS_META_DIR" ]; then
        while IFS= read -r META; do
            if grep -q '"Dirty": true' "$META" 2>/dev/null; then
                REL="${META#"$VFS_META_DIR"/}"
                DATA_FILE="${VFS_DIR}/${REL}"
                if [ -f "$DATA_FILE" ]; then
                    B=$(( $(stat -c %b "$DATA_FILE" 2>/dev/null || echo 0) * 512 ))
                    DIRTY_BYTES=$((DIRTY_BYTES + B))
                    if [ "$DIRTY_COUNT" -lt 15 ]; then
                        printf '    %8s  %s\n' \
                            "$(numfmt --to=iec --suffix=B "$B" 2>/dev/null || echo "$B")" "$REL"
                    fi
                fi
                DIRTY_COUNT=$((DIRTY_COUNT + 1))
            fi
        done < <(find "$VFS_META_DIR" -type f 2>/dev/null)
    fi
    if [ "$DIRTY_COUNT" -eq 0 ]; then
        echo "    None. Nothing is waiting to upload (safe to clear the cache)."
    else
        echo ""
        echo "    ${DIRTY_COUNT} dirty file(s), $(numfmt --to=iec --suffix=B "$DIRTY_BYTES" 2>/dev/null || echo "$DIRTY_BYTES") pinned."
        echo "    [!] DO NOT 'rm -rf' the cache - these have not reached Drive yet."
        echo "        Check for upload errors:"
        echo "          grep -iE 'vfs cache: (failed|error)' ${CACHE_DIR}/rclone.log | tail -20"
    fi

    # ---------------------------------------------------------------
    # 3. Orphans: data files with no metadata. Rclone does not count
    #    these toward the quota, so they are never evicted.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 3. Orphaned files (untracked, never counted or evicted) ---"
    ORPHAN_COUNT=0
    ORPHAN_BYTES=0
    while IFS= read -r DATA_FILE; do
        REL="${DATA_FILE#"$VFS_DIR"/}"
        if [ ! -f "${VFS_META_DIR}/${REL}" ]; then
            B=$(( $(stat -c %b "$DATA_FILE" 2>/dev/null || echo 0) * 512 ))
            ORPHAN_BYTES=$((ORPHAN_BYTES + B))
            if [ "$ORPHAN_COUNT" -lt 15 ]; then
                printf '    %8s  %s\n' \
                    "$(numfmt --to=iec --suffix=B "$B" 2>/dev/null || echo "$B")" "$REL"
            fi
            ORPHAN_COUNT=$((ORPHAN_COUNT + 1))
        fi
    done < <(find "$VFS_DIR" -type f 2>/dev/null)
    if [ "$ORPHAN_COUNT" -eq 0 ]; then
        echo "    None. Every cached file has tracking metadata."
    else
        echo ""
        echo "    ${ORPHAN_COUNT} orphan(s), $(numfmt --to=iec --suffix=B "$ORPHAN_BYTES" 2>/dev/null || echo "$ORPHAN_BYTES") invisible to the quota."
        echo "    These are leftovers (crash, kill -9, or a previously unbounded mount)."
        echo "    They have no pending data and are safe to delete while stopped."
    fi

    # ---------------------------------------------------------------
    # 4. Currently open files - cannot be evicted while held.
    # ---------------------------------------------------------------
    echo ""
    echo "--- 4. Cache files held open right now ---"
    if [ -n "$RCLONE_PID" ] && [ -d "/proc/${RCLONE_PID}/fd" ]; then
        OPEN_LIST=$(find "/proc/${RCLONE_PID}/fd" -type l 2>/dev/null \
            | xargs -r readlink 2>/dev/null | grep "^${VFS_DIR}/" || true)
        if [ -z "$OPEN_LIST" ]; then
            echo "    None. Nothing is pinned by an open handle."
        else
            echo "$OPEN_LIST" | sort -u | head -n 15 | sed "s|^${VFS_DIR}/|    |"
            echo "    (open files cannot be evicted until the reader closes them)"
        fi
    else
        echo "    (cannot inspect - no running process)"
    fi

    # ---------------------------------------------------------------
    # 5. Verdict
    # ---------------------------------------------------------------
    RECLAIM=$((ORPHAN_BYTES / 1024))
    echo ""
    echo "=========================================================="
    echo "  Summary"
    echo "=========================================================="
    printf '  Real usage        : %s\n' "$REAL_H"
    printf '  Pending upload    : %s (must keep)\n' \
        "$(numfmt --to=iec --suffix=B "$DIRTY_BYTES" 2>/dev/null || echo "$DIRTY_BYTES")"
    printf '  Orphaned          : %s (safe to reclaim)\n' \
        "$(numfmt --to=iec --suffix=B "$ORPHAN_BYTES" 2>/dev/null || echo "$ORPHAN_BYTES")"
    echo ""
    if [ "$ORPHAN_COUNT" -gt 0 ] && [ "$RECLAIM" -gt $((REAL_KB / 2)) ]; then
        echo "  => Most of your cache is ORPHANED and invisible to rclone's quota."
        echo "     That is why the size limit never kicks in. Reclaim it with:"
        echo "         systemctl --user stop ${SERVICE_NAME}.service"
        echo "         ./setup_gdrive_mount.sh purge-orphans"
        echo "         systemctl --user start ${SERVICE_NAME}.service"
        echo "     (purge-orphans removes ONLY untracked files, so anything"
        echo "      pending upload is left alone - unlike clear-cache.)"
    elif [ "$DIRTY_COUNT" -gt 0 ] && [ "$DIRTY_BYTES" -gt $((REAL_KB * 1024 / 2)) ]; then
        echo "  => Most of your cache is PENDING UPLOAD and cannot be evicted."
        echo "     Fix the uploads (check the log above); do not delete the cache."
    else
        echo "  => No single dominant cause found above. The most likely"
        echo "     explanation is the running process lacking the limits"
        echo "     (see section 1) - restart the service to apply them."
    fi
    echo ""
}

do_cache() {
    echo ""
    echo "=== VFS Cache Usage ==="
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"

    if [ ! -d "$VFS_DIR" ]; then
        echo "[i] No VFS cache directory at ${VFS_DIR} (nothing cached yet)."
        return 0
    fi

    # Cache files are SPARSE. `du --apparent-size` shows the full logical file
    # size, but only the downloaded chunks occupy real blocks. Plain `du`
    # reports real disk usage -- that is the number that matters.
    REAL=$(du -sh "$VFS_DIR" 2>/dev/null | cut -f1)
    APPARENT=$(du -sh --apparent-size "$VFS_DIR" 2>/dev/null | cut -f1)
    META=$(du -sh "$VFS_META_DIR" 2>/dev/null | cut -f1)

    echo "  Real disk used by cached data : ${REAL:-0}   <-- what fills your disk"
    echo "  Apparent (sparse) size        : ${APPARENT:-0}   <-- misleading, ignore"
    echo "  Metadata (vfsMeta)            : ${META:-0}"
    echo ""
    echo "  Filesystem holding the cache:"
    df -h "${CACHE_DIR}" | sed 's/^/    /'
    echo ""
    echo "  Largest cached files (real usage):"
    find "$VFS_DIR" -type f -printf '%b %p\0' 2>/dev/null \
        | sort -z -rn \
        | head -z -n 10 \
        | while IFS=' ' read -r -d '' blocks path; do
              # %b is 512-byte blocks actually allocated -> real bytes
              printf '    %6s  %s\n' \
                  "$(numfmt --to=iec --suffix=B $((blocks * 512)) 2>/dev/null || echo $((blocks * 512)))" \
                  "${path#"$VFS_DIR"/}"
          done
    echo ""
    echo ""
    echo "  Rclone's own view of the cache (last cleaner run):"
    if [ -f "${CACHE_DIR}/rclone.log" ]; then
        grep "vfs cache: cleaned:" "${CACHE_DIR}/rclone.log" | tail -n 3 | sed 's/^/    /' \
            || echo "    (no cleaner lines yet)"
    else
        echo "    (no log file yet)"
    fi
}

do_purge_orphans() {
    VFS_DIR="${CACHE_DIR}/vfs"
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"

    echo ""
    echo "=== Purge Orphaned Cache Files ==="
    echo "Removes ONLY cache files with no tracking metadata. Files pending"
    echo "upload are left untouched, so this cannot lose data."
    echo ""

    if [ ! -d "$VFS_DIR" ]; then
        echo "[i] No VFS cache directory."
        return 0
    fi

    if systemctl --user is-active --quiet "${SERVICE_NAME}.service"; then
        echo "[!] The mount is running. Stop it first so rclone is not writing"
        echo "    to these files while we delete them:"
        echo "        systemctl --user stop ${SERVICE_NAME}.service"
        return 1
    fi

    ORPHANS=$(mktemp)
    TOTAL=0
    COUNT=0
    while IFS= read -r DATA_FILE; do
        REL="${DATA_FILE#"$VFS_DIR"/}"
        if [ ! -f "${VFS_META_DIR}/${REL}" ]; then
            B=$(( $(stat -c %b "$DATA_FILE" 2>/dev/null || echo 0) * 512 ))
            TOTAL=$((TOTAL + B))
            COUNT=$((COUNT + 1))
            printf '%s\n' "$DATA_FILE" >> "$ORPHANS"
        fi
    done < <(find "$VFS_DIR" -type f 2>/dev/null)

    if [ "$COUNT" -eq 0 ]; then
        echo "[i] No orphaned files found."
        rm -f "$ORPHANS"
        return 0
    fi

    echo "Found ${COUNT} orphaned file(s) totalling $(numfmt --to=iec --suffix=B "$TOTAL" 2>/dev/null || echo "$TOTAL"):"
    head -n 10 "$ORPHANS" | sed "s|^${VFS_DIR}/|    |"
    [ "$COUNT" -gt 10 ] && echo "    ... and $((COUNT - 10)) more"
    echo ""
    read -p "Delete these ${COUNT} file(s)? (y/N): " CONFIRM
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo "Cancelled."
        rm -f "$ORPHANS"
        return 0
    fi

    while IFS= read -r F; do rm -f "$F"; done < "$ORPHANS"
    rm -f "$ORPHANS"
    find "$VFS_DIR" -type d -empty -delete 2>/dev/null || true
    echo "[✓] Reclaimed $(numfmt --to=iec --suffix=B "$TOTAL" 2>/dev/null || echo "$TOTAL")."
    echo "    Cache is now: $(du -sh "$VFS_DIR" 2>/dev/null | cut -f1)"
}

do_clear_cache() {
    echo ""
    echo "=== Clear VFS Cache ==="
    echo "[!] The cache can hold files that have NOT finished uploading to Drive."
    echo "    Deleting it while those are pending means DATA LOSS."
    echo ""

    # Hard stop if anything is still pending upload. Counting dirty items is
    # cheap and prevents the single most destructive mistake available here.
    VFS_META_DIR="${CACHE_DIR}/vfsMeta"
    DIRTY_N=0
    DIRTY_B=0
    if [ -d "$VFS_META_DIR" ]; then
        while IFS= read -r META; do
            if grep -q '"Dirty": true' "$META" 2>/dev/null; then
                REL="${META#"$VFS_META_DIR"/}"
                SRC="${CACHE_DIR}/vfs/${REL}"
                if [ -f "$SRC" ]; then
                    DIRTY_B=$((DIRTY_B + $(( $(stat -c %b "$SRC" 2>/dev/null || echo 0) * 512 )) ))
                fi
                DIRTY_N=$((DIRTY_N + 1))
            fi
        done < <(find "$VFS_META_DIR" -type f 2>/dev/null)
    fi

    if [ "$DIRTY_N" -gt 0 ]; then
        echo "  ######################################################"
        echo "  #  REFUSING TO CLEAR - DATA WOULD BE LOST            #"
        echo "  ######################################################"
        echo ""
        echo "  ${DIRTY_N} file(s) totalling $(numfmt --to=iec --suffix=B "$DIRTY_B" 2>/dev/null || echo "$DIRTY_B") have NOT reached Google Drive."
        echo "  They exist ONLY here. Deleting the cache destroys them."
        echo ""
        echo "  Do this instead:"
        echo "    1. Find out why uploads are failing:"
        echo "         ./setup_gdrive_mount.sh uploads"
        echo "    2. Copy the pending data somewhere safe:"
        echo "         ./setup_gdrive_mount.sh rescue-pending ~/drive-backup"
        echo "    3. Only then, if you still want to wipe the cache, re-run"
        echo "       this command with the override:"
        echo "         ./setup_gdrive_mount.sh clear-cache --force"
        echo ""
        if [ "$FORCE_CLEAR" != true ]; then
            return 1
        fi
        echo "  [!] --force given: proceeding despite ${DIRTY_N} pending file(s)."
        read -p "  Type DELETE to confirm permanent loss: " FORCE_CONFIRM
        if [ "$FORCE_CONFIRM" != "DELETE" ]; then
            echo "  Cancelled."
            return 1
        fi
    fi

    if systemctl --user is-active --quiet "${SERVICE_NAME}.service"; then
        echo "[i] Service is running. Asking rclone to flush pending uploads first..."
        echo "    (stopping the service triggers a clean unmount + writeback)"
        read -p "Stop the mount and clear the cache now? (y/N): " CONFIRM
        if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
            echo "Cancelled."
            return 0
        fi
        systemctl --user stop "${SERVICE_NAME}.service" || true
        # Give writeback a moment to settle after unmount.
        sleep 2
    else
        read -p "Service is stopped. Clear the cache directory now? (y/N): " CONFIRM
        if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
            echo "Cancelled."
            return 0
        fi
    fi

    if [ -d "${CACHE_DIR}/vfs" ]; then
        rm -rf "${CACHE_DIR}/vfs" "${CACHE_DIR}/vfsMeta"
        echo "[✓] Cleared ${CACHE_DIR}/vfs and ${CACHE_DIR}/vfsMeta"
    else
        echo "[i] Nothing to clear."
    fi

    read -p "Restart the mount service? (Y/n): " RESTART
    if [[ ! "$RESTART" =~ ^[Nn]$ ]]; then
        systemctl --user start "${SERVICE_NAME}.service"
        echo "[✓] Service restarted."
    fi
}

do_setup() {
    echo "=== Google Drive Fast Mount Setup ==="

    # 1. Ensure rclone is installed
    if ! command -v rclone &> /dev/null; then
        echo "[+] Installing rclone..."
        if command -v apt-get &> /dev/null; then
            sudo apt-get update -qq && sudo apt-get install -y -qq rclone
        else
            curl -s https://rclone.org/install.sh | sudo bash
        fi
    else
        echo "[✓] rclone is already installed ($(rclone version | head -n 1))"
    fi

    # 2. Ensure fuse / fusermount is available
    if ! command -v fusermount &> /dev/null && ! command -v fusermount3 &> /dev/null; then
        echo "[+] Installing fuse..."
        if command -v apt-get &> /dev/null; then
            sudo apt-get install -y -qq fuse3 || sudo apt-get install -y -qq fuse
        fi
    fi

    # Enable user_allow_other in /etc/fuse.conf if needed
    if [ -f /etc/fuse.conf ]; then
        if ! grep -q "^user_allow_other" /etc/fuse.conf; then
            echo "[+] Enabling user_allow_other in /etc/fuse.conf..."
            echo "user_allow_other" | sudo tee -a /etc/fuse.conf > /dev/null
        fi
    fi

    # 3. Handle Rclone Configuration & Optional SCP Import
    mkdir -p "${RCLONE_CONF_DIR}"

    if [ -f "$RCLONE_CONF" ]; then
        echo "[✓] Existing rclone configuration found at ${RCLONE_CONF}."
        read -p "Do you want to re-import/overwrite rclone config via SCP from another server? (y/N): " USE_SCP
    else
        read -p "No rclone config found. Do you want to SCP your existing rclone config from another server? (y/N): " USE_SCP
    fi

    if [[ "$USE_SCP" =~ ^[Yy]$ ]]; then
        read -p "Enter source SSH user and server (e.g. ubuntu@192.168.1.50 or my-server): " REMOTE_SERVER
        if [ -n "$REMOTE_SERVER" ]; then
            echo "[+] Fetching ${RCLONE_CONF} from ${REMOTE_SERVER}:~/.config/rclone/rclone.conf..."
            scp "${REMOTE_SERVER}:~/.config/rclone/rclone.conf" "${RCLONE_CONF}"
            echo "[✓] Successfully copied rclone.conf via SCP!"
        else
            echo "[!] No server specified. Skipping SCP."
        fi
    fi

    # If rclone.conf is still missing or remote doesn't exist, prompt for rclone config
    if [ ! -f "$RCLONE_CONF" ] || ! grep -q "\[${REMOTE_NAME}\]" "$RCLONE_CONF"; then
        echo "[!] Remote '${REMOTE_NAME}' not found in ${RCLONE_CONF}."
        echo "[+] Running 'rclone config' to set up '${REMOTE_NAME}'..."
        echo "    Please create a remote named '${REMOTE_NAME}' during configuration."
        rclone config
    fi

    # 4. Create directories
    echo "[+] Creating mount and cache directories..."
    mkdir -p "${MOUNT_DIR}"
    mkdir -p "${SYSTEMD_USER_DIR}"
    mkdir -p "${CACHE_DIR}"

    # 5. Create optimized systemd user service
    SERVICE_FILE="${SYSTEMD_USER_DIR}/${SERVICE_NAME}.service"
    echo "[+] Writing systemd user service to ${SERVICE_FILE}..."

    if [ "$READ_ONLY" = false ]; then
        read -p "Mount as read-only? (y/N): " ASK_READONLY
        if [[ "$ASK_READONLY" =~ ^[Yy]$ ]]; then
            READ_ONLY=true
        fi
    fi

    # Locate fusermount. Arch and other fuse3-only distros ship
    # /usr/bin/fusermount3 with no fuse2 compatibility symlink, so a
    # hardcoded /bin/fusermount makes ExecStop fail silently. When that
    # happens a failed start leaves the FUSE endpoint mounted, and every
    # retry then hits "mountpoint is not empty" - an endless restart loop.
    FUSERMOUNT_BIN=""
    for CAND in /usr/bin/fusermount3 /bin/fusermount3 /usr/bin/fusermount /bin/fusermount; do
        if [ -x "$CAND" ]; then FUSERMOUNT_BIN="$CAND"; break; fi
    done
    if [ -z "$FUSERMOUNT_BIN" ]; then
        echo "[!] No fusermount/fusermount3 found. Install fuse3:"
        echo "      Arch:   sudo pacman -S fuse3"
        echo "      Debian: sudo apt install fuse3"
        echo "      Fedora: sudo dnf install fuse3"
        return 1
    fi
    echo "[i] Using ${FUSERMOUNT_BIN} for unmounting."

    # Likewise resolve rclone rather than assuming /usr/bin/rclone: manual
    # installs and Homebrew land in /usr/local/bin, and systemd needs an
    # absolute path (units run without a useful PATH).
    RCLONE_BIN=$(command -v rclone 2>/dev/null) || RCLONE_BIN=""
    [ -z "$RCLONE_BIN" ] && RCLONE_BIN="/usr/bin/rclone"
    echo "[i] Using ${RCLONE_BIN} as the rclone binary."

    MOUNT_FLAGS=""
    if [ "$READ_ONLY" = true ]; then
        MOUNT_FLAGS=" --read-only"
        echo "[i] Mounting in read-only mode."
    else
        echo "[i] Mounting in read-write mode."
    fi

    # Ask the binary which flags it actually understands. Distro builds lag
    # upstream (Ubuntu 22.04 ships 1.60, which has no
    # --vfs-cache-min-free-space), and rclone treats an unknown flag as a
    # fatal error - the mount never starts. Probing beats hardcoding a
    # version table, since it also covers -DEV builds with backported flags.
    RCLONE_MOUNT_HELP=$("$RCLONE_BIN" mount --help 2>&1) || RCLONE_MOUNT_HELP=""
    RCLONE_GLOBAL_HELP=$("$RCLONE_BIN" help flags 2>&1) || RCLONE_GLOBAL_HELP=""
    supports_flag() {
        case "${RCLONE_MOUNT_HELP}${RCLONE_GLOBAL_HELP}" in
            *"$1"*) return 0 ;;
            *) return 1 ;;
        esac
    }

    # Built incrementally so unsupported flags are simply omitted.
    OPT_FLAGS=""          # 4-space indent, for the systemd unit
    OPT_FLAGS_RUNNER=""   # 8-space indent, for the standalone runner
    SKIPPED_FLAGS=""
    add_flag() {  # add_flag <flag> <value-or-empty>
        if supports_flag "$1"; then
            if [ -n "${2:-}" ]; then
                OPT_FLAGS="${OPT_FLAGS}    $1 $2 \\\\\n"
                OPT_FLAGS_RUNNER="${OPT_FLAGS_RUNNER}        $1 $2 \\\\\n"
            else
                OPT_FLAGS="${OPT_FLAGS}    $1 \\\\\n"
                OPT_FLAGS_RUNNER="${OPT_FLAGS_RUNNER}        $1 \\\\\n"
            fi
        else
            SKIPPED_FLAGS="${SKIPPED_FLAGS} $1"
        fi
    }

    add_flag --vfs-cache-min-free-space "${VFS_CACHE_MIN_FREE}"
    add_flag --drive-chunk-size         "${DRIVE_CHUNK_SIZE}"
    add_flag --drive-upload-cutoff      "${DRIVE_CHUNK_SIZE}"
    add_flag --drive-pacer-min-sleep    "${DRIVE_PACER_MIN_SLEEP}"
    add_flag --drive-pacer-burst        "${DRIVE_PACER_BURST}"
    add_flag --stats                    "30s"
    add_flag --stats-one-line           ""

    if [ -n "$SKIPPED_FLAGS" ]; then
        echo "[!] rclone $("$RCLONE_BIN" version 2>/dev/null | head -n1 | awk '{print $2}') does not support:${SKIPPED_FLAGS}"
        echo "    Omitting them so the mount can start. To get them, upgrade:"
        echo "      sudo -v ; curl https://rclone.org/install.sh | sudo bash"
        case "$SKIPPED_FLAGS" in
            *vfs-cache-min-free-space*)
                echo "    NOTE: without --vfs-cache-min-free-space the cache is bounded"
                echo "          only by --vfs-cache-max-size (${VFS_CACHE_MAX_SIZE}), not by free disk."
                ;;
        esac
    fi

    # Type=notify makes systemd wait for the mount to be ready and surfaces
    # live VFS cache stats in `systemctl --user status`. sd-notify support has
    # been in rclone for many years (well before 1.52); the >=1.52 gate below
    # is a conservative floor, not the version it was introduced in. Anything
    # older falls back to `simple`, which still works.
    SERVICE_TYPE="simple"
    RCLONE_VER=$(rclone version 2>/dev/null | head -n1 | grep -oE '[0-9]+\.[0-9]+' | head -n1)
    if [ -n "$RCLONE_VER" ]; then
        RC_MAJOR=${RCLONE_VER%%.*}
        RC_MINOR=${RCLONE_VER##*.}
        if [ "$RC_MAJOR" -gt 1 ] 2>/dev/null || \
           { [ "$RC_MAJOR" -eq 1 ] && [ "$RC_MINOR" -ge 52 ]; } 2>/dev/null; then
            SERVICE_TYPE="notify"
        fi
    fi
    echo "[i] Using systemd Type=${SERVICE_TYPE} (rclone ${RCLONE_VER:-unknown})"

    cat <<EOF > "${SERVICE_FILE}"
[Unit]
Description=Rclone Mount for Google Drive (${REMOTE_NAME})
After=network-online.target
Wants=network-online.target

[Service]
Type=${SERVICE_TYPE}
# Clear any stale FUSE endpoint left by a previous failed start, otherwise
# rclone refuses to mount over it and the service restart-loops forever.
# '-' prefix: ignore failure when there is nothing mounted (the normal case).
ExecStartPre=-${FUSERMOUNT_BIN} -u -z ${MOUNT_DIR}
ExecStart=${RCLONE_BIN} mount ${REMOTE_NAME}: ${MOUNT_DIR} \\
    --config ${RCLONE_CONF} \\
    --cache-dir ${CACHE_DIR} \\
    --vfs-cache-mode full \\
    --vfs-cache-max-size ${VFS_CACHE_MAX_SIZE} \\
    --vfs-cache-max-age ${VFS_CACHE_MAX_AGE} \\
    --vfs-cache-poll-interval ${VFS_CACHE_POLL_INTERVAL} \\
    --allow-other \\
    --poll-interval 1m \\
    --dir-cache-time 1000h \\
    --attr-timeout 1000h \\
    --vfs-read-chunk-size 32M \\
    --vfs-read-chunk-size-limit 1G \\
    --buffer-size 32M \\
    --transfers ${TRANSFERS} \\
$(printf "${OPT_FLAGS}")
    --log-file ${CACHE_DIR}/rclone.log \\
    --log-level INFO${MOUNT_FLAGS}
ExecStop=${FUSERMOUNT_BIN} -u -z ${MOUNT_DIR}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF

    # 6/7. Start the mount. Containers and WSL usually have no systemd as
    # PID 1, so `systemctl --user` cannot work at all there - writing a unit
    # and then failing to start it is confusing. Detect and fall back to a
    # plain background process with an equivalent helper script.
    if ! have_systemd; then
        echo ""
        echo "[!] systemd is not running as PID 1 (container, WSL, or similar)."
        echo "    The unit file was still written to:"
        echo "      ${SERVICE_FILE}"
        echo "    but it cannot be started with systemctl here."
        echo ""
        write_runner_script
        echo "[i] Created ${RUNNER_SCRIPT} to run the same mount without systemd."
        echo ""
        echo "    Start it:   ${RUNNER_SCRIPT} start"
        echo "    Stop it:    ${RUNNER_SCRIPT} stop"
        echo "    Status:     ${RUNNER_SCRIPT} status"
        echo ""
        echo "    NOTE: FUSE in a container needs the host to allow it:"
        echo "      docker run --cap-add SYS_ADMIN --device /dev/fuse \\"
        echo "                 --security-opt apparmor:unconfined ..."
        echo "    Without those the mount will fail no matter how it is started."
        echo ""
        read -p "Start the mount now? (Y/n): " START_NOW
        if [[ ! "$START_NOW" =~ ^[Nn]$ ]]; then
            "${RUNNER_SCRIPT}" start || true
        fi
        echo "=========================================================="
        echo " [✓] Setup complete (non-systemd mode)"
        echo " Mount location: ${MOUNT_DIR}"
        echo " Control:        ${RUNNER_SCRIPT} {start|stop|status}"
        echo " Logs:           ${CACHE_DIR}/rclone.log"
        echo "=========================================================="
        return 0
    fi

    # Enable linger so the mount survives SSH logout
    if command -v loginctl &> /dev/null; then
        echo "[+] Enabling user linger..."
        loginctl enable-linger "${USER}" || true
    fi

    echo "[+] Enabling and starting ${SERVICE_NAME}.service..."
    systemctl --user daemon-reload
    systemctl --user enable --now "${SERVICE_NAME}.service"

    echo "=========================================================="
    echo " [✓] Google Drive Mount Setup Complete!"
    echo " Mount location: ${MOUNT_DIR}"
    echo " Service status: systemctl --user status ${SERVICE_NAME}.service"
    echo " Logs:           ${CACHE_DIR}/rclone.log"
    echo "=========================================================="
}

# --- CLI Arguments or Main Menu ---
case "$1" in
    mount|setup)
        shift
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --readonly) READ_ONLY=true; shift ;;
                *) shift ;;
            esac
        done
        do_setup
        ;;
    unmount|stop)
        do_unmount
        ;;
    status)
        do_status
        ;;
    cache)
        do_cache
        ;;
    diagnose)
        do_diagnose
        ;;
    purge-orphans)
        do_purge_orphans
        ;;
    uploads)
        do_uploads
        ;;
    speedcheck)
        do_speedcheck
        ;;
    watch)
        do_watch
        ;;
    logtail)
        do_logtail
        ;;
    doctor)
        do_doctor
        ;;
    trymount)
        do_trymount
        ;;
    reupload)
        shift
        do_reupload "$1"
        ;;
    rescue-pending)
        shift
        do_rescue_pending "$1"
        ;;
    clear-cache)
        shift
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --force) FORCE_CLEAR=true; shift ;;
                *) shift ;;
            esac
        done
        do_clear_cache
        ;;
    *)
        echo "=========================================="
        echo "   Google Drive Mount Manager & Setup"
        echo "=========================================="
        echo "1) Setup / Start Google Drive Mount"
        echo "2) Unmount Google Drive"
        echo "3) Check Mount Status & Logs"
        echo "4) Show VFS cache usage (real vs sparse)"
        echo "5) Diagnose why the cache is too big"
        echo "6) Analyse pending uploads / failures"
        echo "7) Check upload speed & throttling"
        echo "8) Purge orphaned files only (data-safe)"
        echo "9) Safely clear entire VFS cache"
        echo "10) Exit"
        echo "=========================================="
        read -p "Select an action [1-10]: " ACTION_CHOICE

        case "$ACTION_CHOICE" in
            1) do_setup ;;
            2) do_unmount ;;
            3) do_status ;;
            4) do_cache ;;
            5) do_diagnose ;;
            6) do_uploads ;;
            7) do_speedcheck ;;
            8) do_purge_orphans ;;
            9) do_clear_cache ;;
            10) echo "Exiting."; exit 0 ;;
            *) echo "Invalid option."; exit 1 ;;
        esac
        ;;
esac
